version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Mongo2022!
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:Mongo2022!@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: Mongo2022!
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Mongo2022!
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongo
    networks:
      - mongo-compose-network

networks:
    mongo-compose-network:
      driver: bridge

volumes:
    mongodata: